# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'player.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from config import token


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(330, 426)
        MainWindow.setStyleSheet("background-color: #1c1c1e;\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 331, 431))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")

        #bot = telebot.TeleBot(token)
        # Авторизация бота

        #audios = bot.

        self.song = QtWidgets.QWidget(self.gridLayoutWidget)
        self.song.setEnabled(True)
        self.song.setMaximumSize(QtCore.QSize(16777215, 80))
        self.song.setObjectName("song")

        self.title = QtWidgets.QLabel(self.song)
        self.title.setGeometry(QtCore.QRect(100, 10, 41, 31))
        self.title.setStyleSheet("color: #FFF;")
        self.title.setObjectName("title")

        self.author = QtWidgets.QLabel(self.song)
        self.author.setGeometry(QtCore.QRect(100, 40, 91, 16))
        self.author.setStyleSheet("color: #FFF;")
        self.author.setObjectName("author")

        self.cover = QtWidgets.QLabel(self.song)
        self.cover.setEnabled(True)
        self.cover.setGeometry(QtCore.QRect(10, 10, 61, 61))
        self.cover.setMaximumSize(QtCore.QSize(5000, 6000))
        self.cover.setSizeIncrement(QtCore.QSize(0, 0))
        self.cover.setBaseSize(QtCore.QSize(100, 100))
        self.cover.setStyleSheet("border-radius: 30px;")
        self.cover.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.cover.setText("")
        self.cover.setPixmap(QtGui.QPixmap("../Trench_cover.jpg"))
        self.cover.setScaledContents(True)
        self.cover.setObjectName("cover")

        self.duration = QtWidgets.QLabel(self.song)
        self.duration.setGeometry(QtCore.QRect(210, 30, 31, 16))
        self.duration.setStyleSheet("color: #FFF;")
        self.duration.setObjectName("duration")

        self.gridLayout.addWidget(self.song, 0, 0, 1, 1)


        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "Chlorine"))
        self.author.setText(_translate("MainWindow", "twenty one pilots"))
        self.duration.setText(_translate("MainWindow", "2:07"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
